### ISSUE TITLE
rust 1.10 for jethro branch

### ISSUE THREAD

**Issue by tekjar** [meta-rust/meta-rust#82]
Hi. Any plans for bumping version on jethro branch?

**Comment by jmesmon** [comment]
- I'm not aware of anyone working on that
- At the moment, we don't have a specific policy around upgrading release branches, but I feel like it'd make sense to accept patches that update them. There is a bit of a question around what level of compat should be kept in the release branches.

**Comment by derekstraka** [comment]
For yocto, typically only bug fixes go into the stable branches rather than version updates.  Jethro will probably only be actively supported for another couple months until 2.2 comes out in October (https://wiki.yoctoproject.org/wiki/Releases), and then it would move to community support.

That said, with how fast rust moves, I wouldn't be opposed to moving forward as long as the PREFERRED_VERSION is set to the original and the previous version is retained to make sure it doesn't break people using the previous 'stable' version.

**Comment by cardoe** [comment]
So I think end result is that we'll accept a patch to do this as long as retain the existing version and set PREFERRED_VERSION to the old version to not break people that have packages that won't build with 1.10. However none of the current maintainers are working on this so it must be a supplied PR. @kteza1 Are you planning on providing this PR?

**Comment by jmesmon** [comment]
Would it not be more correct to use `DEFAULT_PREFERENCE = "-1"` for preventing automatic selection of newer versions?

**Comment by cardoe** [comment]
So I'm honestly not sure how we'd backport this stuff to jethro without nuking 1.7 since the state of the versions results in something that can't be added alongside each other since the bbclasses conflict since we've changed them significantly and kept the same name (if you recall the `cargo_util` bbclass for example got renamed to `cargo` but there's more than that.)

**Comment by cardoe** [comment]
any @meta-rust/maintainers want to take charge on this or is this a patches welcome request?

**Comment by derekstraka** [comment]
Jethro has moved to community support only and I don't envision anyone doing this backport
